name: prospector
dependencies:
  - python==3.8
  # infrastructure
  - pip
  - ipython
  # scientific computing
  - numpy >= 1.14.2
  - scipy >= 1.1.0
  - matplotlib
  - h5py
  # astro
  - astropy
  # inference
  - corner
  - emcee
  - dynesty
  - pip:
    - fsps
    - astro-sedpy
